### ISSUE TITLE
The videos and slides disappeared.

### ISSUE THREAD

**Issue by ddz16** [atlas-eccv22/atlas-eccv22.github.io#1]
Amazing repository and tutorial! But I can't find the videos and slides in [https://atlas-eccv22.github.io/index.html](https://atlas-eccv22.github.io/index.html). What's wrong with it？
![image](https://user-images.githubusercontent.com/45875562/199386812-0263a77a-ccd5-4871-ab18-d146513d81d6.png)

**Comment by nus-cvml** [comment]
Hi there,

Unfortunately, we lost the recording of Prof. Angela's talk on TAS due to some technical issues from the ECCV's side, hence we are not able to include that on the website for now.

As organization members, we are planning to record another, but that won't be at the top of our list.
  
A recent update has been made to the website and please go and check out the resources available.


Thanks,
ATLAS Organizers
